# Generated by Django 3.0.2 on 2020-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('take', 'Take medicine'), ('prescription', 'Order prescription'), ('appointment', 'Make doctors appointment')], max_length=15),
        ),
    ]
