# Generated by Django 3.0.2 on 2020-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_auto_20200107_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
