# Generated by Django 3.0.2 on 2020-01-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_auto_20200108_0949'),
        ('prescriptions', '0006_auto_20200108_1034'),
    ]

    operations = [
    ]
