# Generated by Django 3.0.2 on 2020-01-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_auto_20200108_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('take', 'Take medicine'), ('order a prescription for', 'Order prescription'), ('make an appointment for', 'Make doctors appointment')], max_length=30),
        ),
    ]
