# Generated by Django 3.0.2 on 2020-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_auto_20200108_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='doses_per_day',
            new_name='number_days_doses',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='number_doses',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('take', 'Take medicine'), ('order prescription', 'Order prescription'), ('make appointment', 'Make doctors appointment')], max_length=30),
        ),
    ]
