# Generated by Django 3.0.2 on 2020-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_auto_20200113_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('take-am', 'Take medicine am'), ('take-mid', 'Take medicine mid'), ('take-pm', 'Take medicine pm'), ('order prescription', 'Order prescription'), ('make appointment', 'Make doctors appointment')], max_length=30),
        ),
    ]
